export const FETCHING_COGNITO_ACCESS_TOKEN = 'FETCHING_COGNITO_ACCESS_TOKEN';
export const FETCHING_COGNITO_ACCESS_TOKEN_SUCCEEDED = 'FETCHING_COGNITO_ACCESS_TOKEN_SUCCEEDED';
export const FETCHING_COGNITO_ACCESS_TOKEN_FAILED = 'FETCHING_COGNITO_ACCESS_TOKEN_FAILED';

export const ACTIVATED_TAB = 'ACTIVATED_TAB';

export const FETCHING_CHAT_RESPONSE = 'FETCHING_CHAT_RESPONSE';
export const FETCHING_CHAT_RESPONSE_SUCCEEDED = 'FETCHING_CHAT_RESPONSE_SUCCEEDED';
export const FETCHING_CHAT_RESPONSE_FAILED = 'FETCHING_CHAT_RESPONSE_FAILED';

export const INVALIDATE_CHAT_RESPONSE = 'INVALIDATE_CHAT_RESPONSE';