export const FETCHING_COGNITO_ACCESS_TOKEN = 'FETCHING_COGNITO_ACCESS_TOKEN';
export const FETCHING_COGNITO_ACCESS_TOKEN_SUCCEEDED = 'FETCHING_COGNITO_ACCESS_TOKEN_SUCCEEDED';
export const FETCHING_COGNITO_ACCESS_TOKEN_FAILED = 'FETCHING_COGNITO_ACCESS_TOKEN_FAILED';

export const ACTIVATED_TAB = 'ACTIVATED_TAB';