export const FETCHING_COGNITO_ACCESS_TOKEN = 'FETCHING_COGNITO_ACCESS_TOKEN';
export const FETCHING_COGNITO_ACCESS_TOKEN_SUCCEEDED = 'FETCHING_COGNITO_ACCESS_TOKEN_SUCCEEDED';
export const FETCHING_COGNITO_ACCESS_TOKEN_FAILED = 'FETCHING_COGNITO_ACCESS_TOKEN_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';
export const ACTIVATED_TAB = 'ACTIVATED_TAB';

export const FETCH_EVALUATION = 'FETCH_EVALUATION';
export const FETCH_EVALUATION_SUCCEEDED = 'FETCH_EVALUATION_SUCCEEDED';
export const FETCH_EVALUATION_FAILED = 'FETCH_EVALUATION_FAILED';

export const FETCHING_CHAT_RESPONSE = 'FETCHING_CHAT_RESPONSE';
export const FETCHING_CHAT_RESPONSE_SUCCEEDED = 'FETCHING_CHAT_RESPONSE_SUCCEEDED';
export const FETCHING_CHAT_RESPONSE_FAILED = 'FETCHING_CHAT_RESPONSE_FAILED';

export const INVALIDATE_CHAT_RESPONSE = 'INVALIDATE_CHAT_RESPONSE';
